# Generated by Django 4.2.6 on 2023-11-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentlike',
            name='unique comment_likes',
        ),
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique post_likes',
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='unique_comment_likes'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('author', 'post'), name='unique_post_likes'),
        ),
    ]
