# Generated by Django 4.2.6 on 2023-11-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_commentlike_unique_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-created_time'], 'verbose_name': 'comment_like', 'verbose_name_plural': 'comment_likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postcommet',
            options={'ordering': ['-created_time'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-created_time'], 'verbose_name': 'post_like', 'verbose_name_plural': 'post_likes'},
        ),
    ]
